name: example
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  flutter_fadein:
    path: ..

flutter:
  uses-material-design: true
