name: flutter_fadein
description: Simple Flutter widget to fade-in your widgets once they are mounted.
version: 2.0.0
author: Charles Crete <charles@cretezy.com>
homepage: https://github.com/Cretezy/flutter_fadein

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
